// <auto-generated />
using Blazor_Ecommerce.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blazor_Ecommerce.Migrations
{
    [DbContext(typeof(TiendaDbContext))]
    partial class TiendaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blazor_Ecommerce.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Consolas de videojuegos de sobremesa y portátiles",
                            Nombre = "Consolas"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Computadoras portátiles para estudio, trabajo y juegos",
                            Nombre = "Notebooks"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Periféricos de entrada para la computadora",
                            Nombre = "Teclados y Mouse"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Auriculares con cable e inalámbricos",
                            Nombre = "Auriculares"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Pantallas para computadora",
                            Nombre = "Monitores"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Hubs, mochilas y otros complementos",
                            Nombre = "Accesorios"
                        });
                });

            modelBuilder.Entity("Blazor_Ecommerce.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Especificaciones")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sku")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("StockActual")
                        .HasColumnType("int");

                    b.Property<int>("StockMinimo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CategoriaId = 1,
                            Descripcion = "Consola de videojuegos para jugar en el televisor.",
                            Especificaciones = "1 TB SSD / salida 4K / 1 control incluido",
                            Marca = "Nexa",
                            Nombre = "Consola de sobremesa 1 TB",
                            Precio = 1100000m,
                            Sku = "CON-0001",
                            StockActual = 15,
                            StockMinimo = 3
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CategoriaId = 1,
                            Descripcion = "Consola portátil para jugar en cualquier lugar.",
                            Especificaciones = "512 GB / pantalla de 7 pulgadas",
                            Marca = "Nexa",
                            Nombre = "Consola portátil 512 GB",
                            Precio = 750000m,
                            Sku = "CON-0002",
                            StockActual = 8,
                            StockMinimo = 2
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            CategoriaId = 2,
                            Descripcion = "Notebook para estudio y trabajo diario.",
                            Especificaciones = "16 GB RAM / 512 GB SSD",
                            Marca = "Orbit",
                            Nombre = "Notebook 15,6 pulgadas Ryzen 5",
                            Precio = 1350000m,
                            Sku = "NOT-0001",
                            StockActual = 10,
                            StockMinimo = 2
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            CategoriaId = 2,
                            Descripcion = "Notebook potente para videojuegos y edición.",
                            Especificaciones = "32 GB RAM / 1 TB SSD / placa de video dedicada",
                            Marca = "Orbit",
                            Nombre = "Notebook gamer 16 pulgadas",
                            Precio = 2400000m,
                            Sku = "NOT-0002",
                            StockActual = 0,
                            StockMinimo = 2
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            CategoriaId = 3,
                            Descripcion = "Teclado mecánico compacto sin bloque numérico.",
                            Especificaciones = "Switches rojos / retroiluminación RGB",
                            Marca = "Vertex",
                            Nombre = "Teclado mecánico TKL",
                            Precio = 95000m,
                            Sku = "TEC-0001",
                            StockActual = 25,
                            StockMinimo = 5
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            CategoriaId = 3,
                            Descripcion = "Mouse cómodo para largas jornadas de trabajo.",
                            Especificaciones = "2400 DPI / Bluetooth y 2,4 GHz",
                            Marca = "Vertex",
                            Nombre = "Mouse inalámbrico ergonómico",
                            Precio = 38000m,
                            Sku = "MOU-0001",
                            StockActual = 40,
                            StockMinimo = 10
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            CategoriaId = 4,
                            Descripcion = "Auriculares plegables para música y llamadas.",
                            Especificaciones = "Bluetooth 5.0 / 30 horas de batería",
                            Marca = "Pulso",
                            Nombre = "Auriculares inalámbricos con micrófono",
                            Precio = 72000m,
                            Sku = "AUR-0001",
                            StockActual = 2,
                            StockMinimo = 5
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            CategoriaId = 4,
                            Descripcion = "Auriculares con sonido envolvente para juegos.",
                            Especificaciones = "USB / sonido 7.1 / micrófono desmontable",
                            Marca = "Pulso",
                            Nombre = "Auriculares gamer 7.1",
                            Precio = 64000m,
                            Sku = "AUR-0002",
                            StockActual = 18,
                            StockMinimo = 5
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            CategoriaId = 5,
                            Descripcion = "Monitor para oficina y estudio.",
                            Especificaciones = "1920x1080 / 75 Hz / panel IPS",
                            Marca = "Kodo",
                            Nombre = "Monitor 24 pulgadas Full HD",
                            Precio = 260000m,
                            Sku = "MON-0001",
                            StockActual = 12,
                            StockMinimo = 3
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            CategoriaId = 5,
                            Descripcion = "Monitor curvo con alta tasa de refresco para juegos.",
                            Especificaciones = "2560x1440 / 144 Hz / panel VA curvo",
                            Marca = "Kodo",
                            Nombre = "Monitor curvo 27 pulgadas 144 Hz",
                            Precio = 480000m,
                            Sku = "MON-0002",
                            StockActual = 6,
                            StockMinimo = 2
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            CategoriaId = 6,
                            Descripcion = "Adaptador para ampliar los puertos de la notebook.",
                            Especificaciones = "HDMI / 3 USB-A / lector SD / carga rápida",
                            Marca = "Pulso",
                            Nombre = "Hub USB-C 7 en 1",
                            Precio = 45000m,
                            Sku = "ACC-0001",
                            StockActual = 30,
                            StockMinimo = 8
                        },
                        new
                        {
                            Id = 12,
                            Activo = false,
                            CategoriaId = 6,
                            Descripcion = "Mochila con compartimento acolchado para notebook.",
                            Especificaciones = "Impermeable / compartimento acolchado",
                            Marca = "Orbit",
                            Nombre = "Mochila para notebook 15,6 pulgadas",
                            Precio = 52000m,
                            Sku = "ACC-0002",
                            StockActual = 20,
                            StockMinimo = 5
                        });
                });

            modelBuilder.Entity("Blazor_Ecommerce.Models.Producto", b =>
                {
                    b.HasOne("Blazor_Ecommerce.Models.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Blazor_Ecommerce.Models.Categoria", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
